<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net80</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RWBaker</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <ApplicationIcon>res/baker.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" Version="1.90.8.1" />
        <PackageReference Include="Microsoft.NET.ILLink.Analyzers" Version="7.0.100-1.23401.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
        <PackageReference Include="Veldrid" Version="4.9.0" />
        <PackageReference Include="Veldrid.ImageSharp" Version="4.9.0" />
        <PackageReference Include="Veldrid.SDL2" Version="4.9.0" />
        <PackageReference Include="Veldrid.SPIRV" Version="1.0.15" />
        <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
        <PackageReference Include="Vortice.ShaderCompiler" Version="1.7.3" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="res\*.spv" />
        <EmbeddedResource Include="res\*.png" />
        <EmbeddedResource Include="res\*.ttf" />
    </ItemGroup>

    <ItemGroup>
        <None Update="cimgui.*"> <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> </None>
        <None Update="shaders/*.*"> <CopyToOutputDirectory>Always</CopyToOutputDirectory> </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Materials\" />
    </ItemGroup>

</Project>
